name: ensure-linted
run-name: Ensure SwiftLint Compliance
on: push
jobs:
  ensure-linted:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mrkdown
        uses: actions/checkout@v4
      - name: Run SwiftLint
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew update
          brew install mint
          mint run realm/SwiftLint@0.56.1
