name: Ensure SwiftLint Compliance
on:
  push:
    paths:
      - "**.swift"
  pull_request:
  workflow_dispatch:
jobs:
  ensure-linted:
    name: Run Linter
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:0.56.1
    steps:
      - name: Checkout mrkdown
        uses: actions/checkout@v4
      - name: Run SwiftLint
        run: swiftlint
